name: Build, Lint, & Test
on:
  pull_request:
    branches:
      - release
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm ci, npm test
      run: |
        npm ci
        npm test
